@isTest
public class SOAPCalloutExampleTest {
    
    @isTest
    static void test_AddCalculator()
    {
        // This causes a fake response to be generated
        Test.setMock(WebServiceMock.class, new SOAPCalculatorCalloutMock());
        // Call the method that invokes a callout
        Double x = 1.0;
        Double y = 2.0;
        Double result = SOAPCalloutExample.addNumers(x, y);
        // Verify that a fake result is returned
        System.assertEquals(3.0, result); 
    }   
}
